Update arm.yml for latest buildx action due to Github buildx@v2 sunsetting
Upgrading to version 3

See URL for info: https://docs.docker.com/build/ci/github-actions/cache/

Error received:
> ERROR: failed to solve: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset